# Generated by Django 4.1.txt.3 on 2024-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
