# Generated by Django 4.1.txt.3 on 2024-11-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
    ]
