# Generated by Django 4.1.txt.3 on 2024-12-03 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Подробное описание')),
                ('delete_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Удаленная задача',
                'verbose_name_plural': 'Удаленные задачи',
            },
        ),
    ]
