# Generated by Django 4.1.3 on 2024-12-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_deletedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priorityTask',
            field=models.CharField(blank=True, choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='typeTask',
            field=models.CharField(blank=True, choices=[('task', 'Задача'), ('bug', 'Баг')], max_length=4, null=True),
        ),
    ]
