# Generated by Django 4.1.3 on 2025-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_deletedtask_prioritytask_deletedtask_typetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedtask',
            name='time_estimate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка времени'),
        ),
        migrations.AddField(
            model_name='deletedtask',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('minutes', 'Минуты'), ('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')], max_length=10, null=True, verbose_name='Единица времени'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_estimate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка времени'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('minutes', 'Минуты'), ('hours', 'Часы'), ('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')], max_length=10, null=True, verbose_name='Единица времени'),
        ),
    ]
