# Generated by Django 4.1.3 on 2025-02-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_deletedtask_time_estimate_deletedtask_time_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedtask',
            old_name='time_estimate',
            new_name='timeEstimate',
        ),
        migrations.RenameField(
            model_name='deletedtask',
            old_name='time_unit',
            new_name='timeUnit',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_estimate',
            new_name='timeEstimate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_unit',
            new_name='timeUnit',
        ),
    ]
