# Generated by Django 4.1.3 on 2025-02-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_rename_time_estimate_deletedtask_timeestimate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedtask',
            name='timeEstimate',
        ),
        migrations.RemoveField(
            model_name='deletedtask',
            name='timeUnit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timeEstimate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='timeUnit',
        ),
    ]
