# Generated by Django 4.1.3 on 2025-02-01 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_remove_deletedtask_timeestimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedtask',
            name='timeEstimateMinutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка времени (в минутах)'),
        ),
        migrations.AddField(
            model_name='task',
            name='timeEstimateMinutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка времени (в минутах)'),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_spent', models.PositiveIntegerField(verbose_name='Затраченное время (в минутах)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='board.task')),
            ],
            options={
                'verbose_name': 'Лог времени',
                'verbose_name_plural': 'Логи времени',
            },
        ),
    ]
