# Generated by Django 4.1.3 on 2025-02-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_task_timeestimateminutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeEstimateMinutes',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Оценка времени (в минутах)'),
        ),
    ]
