# Generated by Django 4.1.3 on 2025-02-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_alter_task_timeestimateminutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedtask',
            name='timeEstimateMinutes',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Оценка времени (в минутах)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeEstimateMinutes',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Оценка времени (в минутах)'),
        ),
    ]
