# Generated by Django 4.1.3 on 2025-02-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_deletedtask_timeestimateminutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedtask',
            name='timeEstimateMinutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка времени (в минутах)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='timeEstimateMinutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка времени (в минутах)'),
        ),
    ]
