# Generated by Django 4.1.3 on 2025-02-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_deletedtask_timeestimateminutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelog',
            old_name='minutes_spent',
            new_name='minutesSpent',
        ),
    ]
