# Generated by Django 4.1.3 on 2025-02-21 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_alter_timelog_owner_alter_timelog_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='id',
        ),
        migrations.AddField(
            model_name='timelog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
