# Generated by Django 4.1.3 on 2025-02-26 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0021_boardgroup_task_group_usersgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardGroup',
            new_name='Group',
        ),
    ]
