# Generated by Django 4.1.3 on 2025-03-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_alter_task_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='board.group', verbose_name='Группы'),
        ),
    ]
