# Generated by Django 4.1.3 on 2025-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_remove_task_group_task_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='boardName',
            field=models.CharField(choices=[('Сделать', 'Todo'), ('В работе', 'Inprogress'), ('На проверке', 'Review'), ('Выполнено', 'Done'), ('Выполнено2', 'Done2')], default='Сделать', max_length=12),
        ),
    ]
