# Generated by Django 5.2.1 on 2025-05-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_alter_task_boardname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='boardName',
            field=models.CharField(choices=[('Сделать', 'Todo'), ('В работе', 'Inprogress'), ('На проверке', 'Review'), ('В тестировании', 'Intest'), ('Выполнено', 'Done')], default='Сделать', max_length=15),
        ),
    ]
